### ISSUE TITLE
Stale libglx symlink

### ISSUE THREAD

**Issue by h1z1** [NVIDIA/nvidia-installer#12]
Not entirely sure when this happened but I noticed X complain about libglx failing to load

```
[   412.948] (II) Loading /usr/lib64/xorg/modules/extensions/libglx.so
[   412.948] (EE) Failed to load /usr/lib64/xorg/modules/extensions/libglx.so: /
usr/lib64/xorg/modules/extensions/libglx.so: cannot open shared object file: No
such file or directory
```

Sure enough, the module appeared bogus

```
$ ls -al /usr/lib64/xorg/modules/extensions/libglx.so
lrwxrwxrwx 1 root root 29 May 22  2019 /usr/lib64/xorg/modules/extensions/libglx.so -> libglxserver_nvidia.so.430.14
$ ls -al /usr/lib64/xorg/modules/extensions/libglx*
libglxserver_nvidia.so            libglx.so
libglxserver_nvidia.so.435.24.02  
$
$ cat /proc/driver/nvidia/version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  435.24.02  Mon Sep 16 21:47:11 UTC 2019
GCC version:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
```

Is this a known issue or should more people be made aware of it?  Fix is trivial just correcting the symlink.

**Comment by aaronp24** [comment]
The driver changed a while back to stop overwriting `libglx.so` and instead leaving it alone and installing a `libglxserver_nvidia.so.<version>` alongside it.

When installing the new driver, the uninstall step should have first restored the original `libglx.so` symlink. However, it's easy for that step to go wrong, for example if your distribution package manager changed the files involved between when the driver was installed and when it was uninstalled.

You should be able to use your distribution's package management tools to find the package that owns `libglx.so` and reinstall it.

**Comment by h1z1** [comment]
This is using the nvidia installer.  There is I believe some logic in it to detect distribution installs, if NVIDIA did make such a change why does their own logic in the installer not detect that??
