### ISSUE TITLE
python 3.10 compat

### ISSUE THREAD

**Issue by abhinavg97** [NVIDIA/nvidia-installer#17]
sudo apt-get install --reinstall ubuntu-drivers-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
Need to get 0 B/53.0 kB of archives.
After this operation, 0 B of additional disk space will be used.
Preconfiguring packages ...
(Reading database ... 285697 files and directories currently installed.)
Preparing to unpack .../ubuntu-drivers-common_1%3a0.9.0~0.20.04.1_amd64.deb ...
Unpacking ubuntu-drivers-common (1:0.9.0~0.20.04.1) over (1:0.9.0~0.20.04.1) ...
Setting up ubuntu-drivers-common (1:0.9.0~0.20.04.1) ...
Setting up nvidia-dkms-470 (470.74-0ubuntu0.20.04.1) ...
update-initramfs: deferring update (trigger activated)
Traceback (most recent call last):
  File "/usr/bin/quirks-handler", line 26, in <module>
    import Quirks.quirkapplier
ModuleNotFoundError: No module named 'Quirks'
dpkg: error processing package nvidia-dkms-470 (--configure):
 installed nvidia-dkms-470 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of nvidia-driver-470:
 nvidia-driver-470 depends on nvidia-dkms-470 (<= 470.74-1); however:
  Package nvidia-dkms-470 is not configured yet.
 nvidia-driver-470 depends on nvidia-dkms-470 (>= 470.74); however:
  Package nvidia-dkms-470 is not configured yet.

dpkg: error processing package nvidia-driver-470 (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Processing triggers for initramfs-tools (0.136ubuntu6.6) ...
update-initramfs: Generating /boot/initrd.img-5.11.0-38-generic
Errors were encountered while processing:
 nvidia-dkms-470
 nvidia-driver-470
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by aaronp24** [comment]
This looks like a problem in Ubuntu packaging, which doesn't use nvidia-installer. If this is still an issue, please file a bug on Ubuntu's Launchpad site.
