### ISSUE TITLE
nvidia-installer removes vfio 

### ISSUE THREAD

**Issue by zbsarashki** [NVIDIA/nvidia-installer#24]
While testing gpu-operator on a cloud platform, we noticed that vfio and vfio_iommu_type1, vfio_mdev, and mdev were removed in a call to: test_kernel_modules from install_kernel_modules. This test can cause problems on a system operation when vfio is used by another application. Is there an option to disable this test?

**Comment by aaronp24** [comment]
You can skip the test-load of the newly-built kernel modules with the `--skip-module-load` option. Note though that it's possible for Kbuild to succeed but create a kernel module that can't be loaded, and skipping this step will allow such a module to be installed.
