### ISSUE TITLE
A suggestion: Import and export global settings and 3d program settings

### ISSUE THREAD

**Issue by Chrometastic** [NVIDIA/nvidia-installer#26]
You can backup and restore profiles by going to this path: C:\ProgramData\NVIDIA Corporation\Drs

And backing up nvdrsdb0.bin ( which is global settings)
and backing up nvdrsdb1.bin (which is 3d application settings) 

It would be nice considering that you can make a change, like forcing 16x AA to all games globally.... 
But when you install a new driver, that setting gets wiped. 

I wish this was a setting that can be changed, and implemented when you install a new driver.

**Comment by aaronp24** [comment]
This repository contains the source code to the Linux driver installer, so unfortunately it isn't relevant to this request. Closing.
