### ISSUE TITLE
Musl support?

### ISSUE THREAD

**Issue by Footsiefat** [NVIDIA/nvidia-installer#27]
When will Nvidia drivers support musl?

**Comment by aaronp24** [comment]
We have no plans to support musl builds of the driver at this time. In addition, this repository is for the graphics driver installer, so it's not really relevant to the rest of the driver. If you want to discuss the driver itself, there's a thread about it on the forum: https://forums.developer.nvidia.com/t/provide-driver-for-muslc-to-install-it-in-musl-distros/219586
