### ISSUE TITLE
What's the meaning of orphaned options

### ISSUE THREAD

**Issue by Forsworns** [NVIDIA/nvidia-installer#30]
I once use `mkprecompiled` to build caches for my driver modules. Recently I read your source code and find it seems I can use `nvidia-installer --add-this-kernel` to generate a prebuilt package, which seems more concise.

But I found this option is "orphaned options". Does it means this option is deprecated or unstable? But I found it has been there 13 years ago since
[260.19.04](https://github.com/NVIDIA/nvidia-installer/commit/f2fb01961579041379a86b96e4f904fd26232749). Can I rely on this option?

https://github.com/NVIDIA/nvidia-installer/blob/bf26ab9625e37986884e1fa7d9652da41e09c908/option_table.h#L715-L719

**Comment by aaronp24** [comment]
The comment is referring to the way the code used to be structured way back in 1.0-7667. The options were defined in the [`long_options[]` array](https://github.com/NVIDIA/nvidia-installer/blob/919fc87075a0b604d316b7d91fca592eba64829e/nvidia-installer.c#L495) and the help text lived in the [`print_advanced_options_args_only`](https://github.com/NVIDIA/nvidia-installer/blob/919fc87075a0b604d316b7d91fca592eba64829e/nvidia-installer.c#L171) function. The [1.0-8174](https://github.com/NVIDIA/nvidia-installer/commit/a99e5e558fc9e279eeee2b76187766ac1dde19cf) release moved both the option definitions and their help text into a single [`__options` array](https://github.com/NVIDIA/nvidia-installer/blob/a99e5e558fc9e279eeee2b76187766ac1dde19cf/option_table.h#L46) in option_table.h. The "orphaned options" were ones that existed in `long_options[]` but didn't have corresponding help text in `print_advanced_options_args_only`. 16 years later, no one has bothered to write help text for them so they're still there in the orphan section.

To make a long story short, these options are still supported.
