### ISSUE TITLE
gbm-backend-dir is available in the options table but not usable with the installer

### ISSUE THREAD

**Issue by adithyaj** [NVIDIA/nvidia-installer#31]
`GBM_BACKEND_DIR_OPTION` is an option listed by the options table and listed within the advanced options of the nvidia-installer via `--gbm-backend-dir`. However, when I provide that option to nvidia-installer it errors out because it doesn't check for it in `parse_commandline`.

Without this option, there is no way to update the library installation directory to a non-default directory.

**Comment by aaronp24** [comment]
Whoops, sorry about that. We filed internal bug number 4457480 to track getting this fixed.

**Comment by aaronp24** [comment]
This was fixed in the 535 series.
