### ISSUE TITLE
Problem with Cuda 8.0 in Ubuntu 16.04

### ISSUE THREAD

**Issue by lincoln2010** [NVIDIA/nvidia-installer#5]
Dear hosters:

The problem occurred when I tried to run samples matrixMulCUBLAS it displays:
[Matrix Multiply CUBLAS] - Starting...
cudaGetDevice returned error code 30, line(166)
My machine info:
Ubuntu 16.04lts
GTX 1080 graphical card
Cuda Toolkit 8.0.44-21122537
However, when I try to run nvidia-smi, it works fine.

Best

**Comment by lincoln2010** [comment]
And every other applications based on Cuda also failed.

**Comment by aaronp24** [comment]
This doesn't sound like an installer problem. I'd recommend looking for help on the CUDA forums at https://devtalk.nvidia.com/
