### ISSUE TITLE
nvidia installer can't find stdarg.h

### ISSUE THREAD

**Issue by afadli** [NVIDIA/nvidia-installer#6]
when i run the nvidia installer it fails with the error log attached.
am i missing a header?

it is ubuntu 16.04 , GTX 1080 TI.

[nvidia-installer.log](https://github.com/NVIDIA/nvidia-installer/files/1374048/nvidia-installer.log)

**Comment by aaronp24** [comment]
stdarg.h normally comes from the compiler. Is it possible your compiler installation got corrupted somehow? Does compiling other software that uses stdarg.h work?

Just to double-check since nvidia-installer.log doesn't capture it, but which compiler does /usr/bin/cc point to?

**Comment by afadli** [comment]
i reinstalled the gcc.
nvidia-smi gives me:
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

and dpkg -l | grep nvidia : 
ii  nvidia-387                            387.12-0ubuntu0~gpu16.04.1         
        amd64        NVIDIA binary driver - version 387.12
ii  nvidia-387-dev                        387.12-0ubuntu0~gpu16.04.1                 amd64        NVIDIA binary Xorg driver development files
ii  nvidia-cuda-dev                       7.5.18-0ubuntu1                            amd64        NVIDIA CUDA development files
ii  nvidia-cuda-doc                       7.5.18-0ubuntu1                            all          NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb                       7.5.18-0ubuntu1                            amd64        NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit                   7.5.18-0ubuntu1                            amd64        NVIDIA CUDA development toolkit
ii  nvidia-modprobe                       384.81-0ubuntu1                            amd64        Load the NVIDIA kernel driver and create device files
ii  nvidia-opencl-icd-387                 387.12-0ubuntu0~gpu16.04.1                 amd64        NVIDIA OpenCL ICD
ii  nvidia-prime                          0.8.2                                      amd64        Tools to enable NVIDIA's Prime
ii  nvidia-profiler                       7.5.18-0ubuntu1                            amd64        NVIDIA Profiler for CUDA and OpenCL
ii  nvidia-settings                       384.90-0ubuntu0~gpu16.04.1                 amd64        Tool for configuring the NVIDIA graphics driver
ii  nvidia-visual-profiler                7.5.18-0ubuntu1                            amd64        NVIDIA Visual Profiler for CUDA and OpenCL

i see that the nvidia-modprobe is for the 384 not fir 387 that is matter? i have a GTX 1080Ti and according to the nvidia website it should work with 387 *NOT* 384.

**Comment by aaronp24** [comment]
I'm going to assume this was a local toolchain problem. Please let me know if you still see this happening.

**Comment by askiiart** [comment]
I've confirmed multiple times that I have `stdarg.h` and that it's not corrupted, but I'm also having this problem. 

The only thing I can find is that the compiler used for the OS was `gcc`, while the compiler the installer is using is `cc`, but I thought those were the same, `cc` just being a link to `gcc`.

Were you able to get this fixed?

**Comment by Exchie** [comment]
> I've confirmed multiple times that I have `stdarg.h` and that it's not corrupted, but I'm also having this problem.
> 
> The only thing I can find is that the compiler used for the OS was `gcc`, while the compiler the installer is using is `cc`, but I thought those were the same, `cc` just being a link to `gcc`.
> 
> Were you able to get this fixed?

Try to softlink `<linux/stdarg.h>` to `<stdarg.h>` in your source/header folder.

**Comment by askiiart** [comment]
This was only a problem with driver 440, when I switched to 470 this was working.
