### ISSUE TITLE
fail build kernel modules kernel 3.10.0-862.2.3.el7.x86_64

### ISSUE THREAD

**Issue by al3x609** [NVIDIA/nvidia-installer#8]
I made an update to centos 7.5 with last kernel aviable but kernel module no load. then re install Nvidia*.run package, and fail kernel module build process. 

installer >> NVIDIA-Linux-x86_64-367.124.run

# uname -a
Linux ngrid 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

#rpm -qa | grep kernel
kernel-3.10.0-862.2.3.el7.x86_64
kernel-headers-3.10.0-862.2.3.el7.x86_64
kernel-devel-3.10.0-862.2.3.el7.x86_64
kernel-tools-libs-3.10.0-862.2.3.el7.x86_64
kernel-tools-3.10.0-862.2.3.el7.x86_64
abrt-addon-kerneloops-2.1.11-50.el7.centos.x86_64

# lspci | grep 'NVIDIA'
0c:00.0 VGA compatible controller: NVIDIA Corporation GK104GL [GRID K2] (rev a1)
0d:00.0 VGA compatible controller: NVIDIA Corporation GK104GL [GRID K2] (rev a1)

------------------------------------------------------------------------------------------------------
ERROR: Failed to run `/usr/sbin/dkms build -m nvidia -v 367.124 -k 3.10.0-862.2.3.el7.x86_64`:
Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
'make' -j6 NV_EXCLUDE_BUILD_MODULES='' KERNEL_UNAME=3.10.0-862.2.3.el7.x86_64 modules......(bad exit status: 2)
Error! Bad return status for module build on kernel: 3.10.0-862.2.3.el7.x86_64 (x86_64)
Consult /var/lib/dkms/nvidia/367.124/build/make.log for more information.
------------------------------------------------------------------------------------------------------
<</var/lib/dkms/nvidia/367.124/build/make.log >>

https://gist.github.com/al3x609/a1348c832ea0f5ffd318927d078991ee

------------------------------------------------------------------------------------------------------
<<nvidia-installer.log>>

https://gist.github.com/al3x609/e0717d6da49fdb86b3102e6cbf6c947c

**Comment by dadap** [comment]
Hi,

This isn’t a problem with nvidia-installer itself, but rather a failure to build this driver version against the target kernel. RHEL 7.5 backported some changes from newer Linux kernels that are incompatible with older NVIDIA drivers. This particular failure is due to a change to the get_user_pages API that should be fixed with more current versions of the driver.

**Comment by al3x609** [comment]
thans, so much.

How I can safe rollback to 7.4 release centos? 
my apologies, Can you help me with this?, thanks @dadap

**Comment by al3x609** [comment]
@blueardour , yes, update drivers to 

Version: | R367 (370.28)
-- | --


and install a kernel version greater than 4.*
