### ISSUE TITLE
Missing link to /usr/lib/libGL.so

### ISSUE THREAD

**Issue by vollstock** [NVIDIA/nvidia-installer#9]
I am the maintainer of ther [Tooloop open media server](https://github.com/vollstock/Tooloop-OS).
When installting the driver using [this code](https://github.com/vollstock/Tooloop-OS/blob/master/files/scripts/tooloop-install-optional-stuff#L69) it seems, the file `/usr/lib/libGL.so` is missing.

Compiling an opeframeworks app, fails with this message:

    /usr/bin/ld: cannot find -lGL
    collect2: error: ld returned 1 exit status

It’s expecting `/usr/lib/libGL.so` but only `libGL.so.1` is there, which itself is a link to `/usr/lib/x86_64-linux-gnu/libGL.so.1`

When adding a link from `/usr/lib/libGL.so` to `/usr/lib/libGL.so.1` solves that issue.

Therefor in my install script I have this code now:

    # repair link so we can compile GL stuff
    cd /usr/lib
    ln -s libGL.so.1 libGL.so 

Sorry I am not very knowledged with this so I'm asking.
Shouldn't the installer add this link in the first place?

**Comment by aaronp24** [comment]
For new projects, I recommend getting libGL and related libraries from https://github.com/NVIDIA/libglvnd rather than from the NVIDIA driver installer. nvidia-installer checks whether libglvnd's libraries are present at install time to decide what to do.

**Comment by vollstock** [comment]
you mean I shold ship this with my OS?

**Comment by aaronp24** [comment]
Yes, I recommend that.

**Comment by vollstock** [comment]
Thanks, will have a look :-)
